#! /usr/bin/env ruby

test = $*[0] == '--test' && $*.shift && true

if $*[0] == '--help' || $*.length < 1
  print <<'EOM'
Usage: #{File.basename($0)} [--test] name files...
Generate bookmarklet.
EOM
end

local  = 'labs.orezdnu.org/js/bookmarklet/'
github = 'github.com/tarao/bookmarklet/raw/master/js/'
url = %W"
  http://
  #{test ? local : github }
".join('')
name = $*.shift
files = $*.length > 0 ? $* : [ name ]
list = files.map{|f| "'#{url}#{f =~ /\.js$/ ? f : f+'.js'}'"}.join(',')

# See http://d.hatena.ne.jp/murky-satyr/20090121/1232326025
print <<"EOM"
javascript:['#{name}',#{test},#{list},function(d,i,e,z){ARG0=this.pop();ARGV='%s'.split(/\\s+/);z=this.pop();for(i=this.length;--i;d.body.appendChild(e))e=d.createElement('script'),e.src=this[i]+(z&&'?'+encodeURI(Date())||''),e.charset='utf-8'}].reverse()[0](document)
EOM
